### ISSUE TITLE
install

### ISSUE THREAD

**Issue by nyf-yellow** [AHartmaier/pyLabDD#1]
hi, thanks for sharing the code, it helps me a lot.
I met a problem when i try to install and test it
--------------------------------------------------------
====================================================== ERRORS ========================================================
__________________________________________ ERROR collecting tests/test_dd.py __________________________________________
ImportError while importing test module 'D:\software\PythonEnv\pyLabDD\tests\test_dd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\Anaconda\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_dd.py:2: in <module>
    import pylabdd as dd
C:\Users\13127\AppData\Roaming\Python\Python311\site-packages\pylabdd\__init__.py:9: in <module>
    from pylabdd.dislocations import Dislocations
C:\Users\13127\AppData\Roaming\Python\Python311\site-packages\pylabdd\dislocations.py:14: in <module>
    from pylabdd.pkforce import calc_fpk_pbc
E   ImportError: DLL load failed while importing pkforce: 找不到指定的模块。
=============================================== short test summary info ===============================================
ERROR tests/test_dd.py
---------------------------------------------------------------------------------------------------------------------------
I have tried many ways, but i still can't solve it. can you give me some suggestions?

**Comment by AHartmaier** [comment]
I created a full Python version that is easier to install but slower. Please try it. NumPy does no longer support the distutils tool, I will try to find a new way to include the Fortran code.
