### ISSUE TITLE
Theory

### ISSUE THREAD

**Issue by nyf-yellow** [AHartmaier/pyLabDD#2]
hi,Thanks for sharing the code, it really helps me a lot. I have two questions about the theory of dislocation dynamics
1、I can't understand how to calculate the force on dislocations in periodic boundary conditions from the code, could you please introduce the theory  to me?
2、In the process of pk force calculation
you wrote:
	F_{PK}1=σ12bx+σ22by ; F_{PK}2 = σ11bx+σ12by
Is it should be:
         F_{PK}1=σ12bx+σ22by ; F_{PK}2 = -(σ11bx+σ12by)
Looking forward to your reply

**Comment by AHartmaier** [comment]
Thanks for pointing out the error in the FPK array, I corrected it in the new version. 
The calculation of forces under periodic boundary conditions is based on Eqs (2.1.25a) and (2.1.25b) in the PhD thesis of  Linyong Pang "A new O(N) method for modeling and simulating the behavior of a large number of dislocations in anisotropic linear elastic media", Stanford University, USA, 2001. I will try to add some more documentation to that in due course. Please PM me in case of specific questions about the theory.
